### ISSUE TITLE
Dropdown position in hamburger menu

### ISSUE THREAD

**Issue by etorres07** [jenkins-infra/contributor-spotlight#208]
### Reproduction steps

1. Visit https://contributors.jenkins.io/.
2. Reduce screen size until top navigation bar is in hamburger menu mode.
3. Click any item with a dropdown box arrow (e.g. Documentation, Community, Subprojects, etc.)

### Expected Results

The dropdown menu should be located below the clicked option, akin to the full-screen, non-hamburger, menu behavior.

### Actual Results

The dropdown menu is located on the left side of the screen, far from the clicked option.

### Anything else?

Example:
![image](https://github.com/user-attachments/assets/6e88aba2-edff-4366-b2b6-ceede619f3ee)

**Comment by krisstern** [comment]
Thanks for filing this issue @etorres07!

**Comment by Utkarsh-Agarwal-585** [comment]
hi @etorres07 can I start work on this? Please assign it to me

**Comment by krisstern** [comment]
Hi @Utkarsh-Agarwal-585 Thanks for your interest in this issue. However, we do not assign issues, but you are welcome to work on this. Please report your progress here. If  we do not hear back from you regarding your progress or receive a PR from you over the next 7 days, the issue will be released.

**Comment by saurabhraghuvanshii** [comment]
@krisstern is  bug  available , i want  to work on  this

**Comment by krisstern** [comment]
Hi @saurabhraghuvanshii I am not sure if this bug can be fixed on our end (i.e. via contributions to this repo) but you can try to ceate a patch for it.

**Comment by saurabhraghuvanshii** [comment]
hi @krisstern I didn't  understand what is mean by patch .

**Comment by krisstern** [comment]
Hi @saurabhraghuvanshii you should really look up the word on your own using a dictionary of your choice. But basicially according to the Oxford Dictionary of English it can mean:

> 6 Computing a small piece of code inserted into a program to improve its functioning or to correct a fault: a program patch that fixes a bug.

**Comment by saurabhraghuvanshii** [comment]
@krisstern thanks sir .

**Comment by saurabhraghuvanshii** [comment]
@krisstern sorry to ask sir , but after two days of try I am not able to find the file where drop-down code or css code written , even I check main repo code where this same bug arise in Jenkins.io .  I check every single  file.

**Comment by krisstern** [comment]
Hi @saurabhraghuvanshii, if you look carefully at https://github.com/jenkins-infra/contributor-spotlight/blob/53d684565343c35e240eaac24a195fe18333f804/gatsby-ssr.jsx#L12 you will see we actually have a dependency for the header on https://github.com/jenkins-infra/jenkins-io-components. So that may be a good place to start.

**Comment by saurabhraghuvanshii** [comment]
@krisstern thanks sir , I found that components .

**Comment by saurabhraghuvanshii** [comment]
@krisstern  done.

**Comment by krisstern** [comment]
@saurabhraghuvanshii I mean to use the exact syntax in the description so that GitHub will close this issue once that PR is closed in the **description** up top:

<img width="982" alt="Screenshot 2024-11-21 at 12 20 01 AM" src="https://github.com/user-attachments/assets/3bd8c292-3c0b-4b74-b3ca-b9914e20dd89">

Once you have this properly done it will show up on the right-hand side of the PR:

<img width="339" alt="Screenshot 2024-11-21 at 12 18 45 AM" src="https://github.com/user-attachments/assets/9a503709-1c23-4c53-ae4e-147dbc23bc31">

And please just copy and paste and don't get creative with it: `Fixes https://github.com/jenkins-infra/contributor-spotlight/issues/208`. 

Any deviation from this will not work. Thanks!

**Comment by saurabhraghuvanshii** [comment]
@krisstern check it sir

**Comment by krisstern** [comment]
@saurabhraghuvanshii It works now! Let me see how I can get someone to review your PR shortly.

**Comment by saurabhraghuvanshii** [comment]
@krisstern  ok sir .

**Comment by saurabhraghuvanshii** [comment]
Hi @krisstern is any update regrading Pr

**Comment by krisstern** [comment]
Hi @saurabhraghuvanshii I am following up on this for you
